dataset:
  bf_test_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Enhanced_fcim_testset
  bf_training_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Enhanced_fcim_trainset
  bf_validation_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Enhanced_fcim_valset
  noisy_test_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Noisy_testset
  noisy_training_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Noisy_trainset
  noisy_validation_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Noisy_valset
  target_test_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Clean_testset
  target_training_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Clean_trainset
  target_validation_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Multichannel_dataset/Clean_valset
defaults:
- model
- training
- dataset: speech_dataset
model:
  attention: true
  ild_weight: 1
  ipd_weight: 10
  snr_loss_weight: 1
  stoi_weight: 10
